### ISSUE TITLE
Configure use of npm/yarn

### ISSUE THREAD

**Issue by frederickfogerty** [philcockfield/msync#14]
Hey there,

We use `npm` for our package manager. Is there a way we could configure `msync` to use `npm`?

For instance, in `msync publish`, we'd like to run `npm install` instead. Currently the command is `yarn install && npm publish && msync sync`

Thanks 😀

**Comment by philcockfield** [comment]
Hey @frederickfogerty - are you finding the new npm lock file is faster than yarn?

**Comment by frederickfogerty** [comment]
Hey @philcockfield! Yarn is probably still a bit faster, but we were having some issues with yarn (bin executables, module deduping, sym-linking), and found that npm just worked :) 

I think both are viable options, it's just down to personal preference at this point.

**Comment by philcockfield** [comment]
I'll think I'll add this as a configuration option to the `sync.yaml` file.

**Comment by philcockfield** [comment]
Uses NPM now.
